config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root to: "topics#index"

  get 'users/' => 'users#index'

  
  get 'users/:id' => 'users#show', as: :user

  post 'users/' => 'users#create'

  get 'users/:id/edit' => 'users#edit', as: :edit_user
  
  patch 'users/:id' => 'users#update', as: :update_user

  delete 'users/:id' => 'users#destroy'

  
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
  end

  resources :topics do
    resources :subtopics
  end

  get "/subtopics/:id" => 'subtopics#show', as: :subtopic
  get "/subtopics/new" => "subtopics#new", as: :subtopics
  post "/subtopics/new" => "subtopics#create"

    resources :links do
      member do 
        put "like", to: "links#upvote"
      end 
      resources :comments, except: :index
    end  

    namespace :api do
        resources :links, only: [:index, :create, :show], defaults: {format: "json"}
        resources :topics, only: [:index, :create, :show], defaults: {format: "json"}
        resources :subtopics, except: [:topic_id], defaults: {format: "json"}
    end

    

  

  
  
  
  
  

  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :subtopics
  

  def description 
    self.name
  end


  def as_json(options={})
    super(
      {:only => :name, 
      :include => {:subtopics => {:methods => [:link_count]}} 


      })
  end
end

app/controllers/api/topics_controller.rb
module Api
  class TopicsController < ApplicationController
    protect_from_forgery with: :null_session
    respond_to :json

    def index
      topics = Topic.all 
      respond_with topics
    end

    def create
      topic = Topic.new(topic_params)
        if topic.save
          respond_with topic, location: [:api, topic]
        else
          respond_with topic
        end
    end
    
    def show 
      topic = Topic.find(params[:id])
      respond_with topic
    end

    def update
      topic = Topic.find(params[:id])
        if topic.update_attributes(topic_params)  
          head 204
        else
          respond_with topic
        end
    end

    def destroy
      topic = Topic.find(params[:id])
      topic.destroy
      head 204
    end


    private 
    def topic_params
      params.require(:topic).permit(:name)
    end

  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
# before filter to give only administrators the ability to add, edit, and delete topics.
before_action :authenticate_user!, except: [:index, :show]
before_filter :admin, except: [:index, :show]


	def index
		@topics = Topic.all
	end

	def show
		@topic = Topic.find(params[:id])
		@topics = Topic.all
		@subtopics = Subtopic.all
		@links = Link.all
		@link = Link.new
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = Topic.new(topic_params)

		if @topic.save
			redirect_to topics_path
		else
			render :new
		end
	end

	def edit
		@topic = Topic.find(params[:id])
	end

	def update

		@topic = Topic.find(params[:id])

		if @topic.update_attributes(topic_params)
			redirect_to topics_path
		else 
			render "edit"
		end
	end
	
	def destroy
		@topic = Topic.find(params[:id])
		@topic.destroy
		redirect_to :back
	end

	

	private

	def topic_params
		params.require(:topic).permit(:name)
	end

	# custom method for the topics controller, please see before filter above
	def admin
	  authenticate_user!
	  if current_user.admin
	     return
	  else
	     redirect_to root_url
	  end
	end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
  <div class="col-md-11 main">
    <h1 class="col-md-offset-3 col-md-6 text-center subtitle">What are you here to learn about?</h1></br>

    <div class="col-md-offset-1 col-md-10 text-center link-list sidebar"></div></br>

    <div id="topic-menu" class="col-md-12 main nav-style">
      <% @topics.each do |topic| %>

        <div class="col-md-3">
          <button class="btn  dropdown-toggle nav-style text-center" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true"><%= link_to topic.name, topic_path(topic) %>
          <span class="caret"></span>
          </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <% topic.subtopics.each do |subtopic| %>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= link_to subtopic.name, subtopic_path(subtopic) %></a></li>
              <% end %>
            </ul>
        </div>
      <% end %>
    </div>
  </div>


 
  <div class="col-md-1"></div>

  
  <script>
  
  // $(function(){
  //   $.getJSON("api/links", function(response, status, jqXHR){

  //     document.write(response)
  //     // function compare(a,b){      
  //     //   if (a.cached_votes_score > b.cached_votes_score)
  //     //     return -1;
  //     //   if (a.cached_votes_score < b.cached_votes_score)
  //     //     return 1;
  //     //   return 0;
  //     //   console.log(a)
  //     // }
  //     // response.sort(compare);
  //     // console.log(response[0]);

  //     // $(".link-list").html("<p> response[0]</p>");
  //     // $(".link-list").html(
  //     //     "<h3 class='oswald'>Popular Subtopics</h3></br>" +
  //     //     "<ul class='list-unstyled'>" +
  //     //       "<li><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/links/" + response[0].id + "'>" + response[0].url + "</a></h4></li>" +
  //     //       "<li><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/links/" + response[1].id + "'>" + response[1].url + "</a></h4></li>" +
  //     //       "<li><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/links/" + response[2].id + "'>" + response[2].url + "</a></h4></li>" +
  //     //       "<li><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/links/" + response[3].id + "'>" + response[3].url + "</a></h4></li>" +
  //     //       "<li><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/links/" + response[4].id + "'>" + response[4].url + "</a></h4></li>" +
  //     //     "</ul>"

  //     // );


  //   })
  // })  
    
  $(function(){

    $.getJSON("api/subtopics", function(response, status, jqXHR){

      function compare(a,b) {
        if (a.links.length > b.links.length)
           return -1;
        if (a.links.length < b.links.length)
          return 1;
        return 0;
        console.log(a)
      }

      response.sort(compare);

      console.log(response);

      $(".link-list").html(
          "<h2 class='oswald'>Popular Subtopics</h2></br></br>" +
          "<span class='oswald'><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/subtopics/" + response[0].id + "'>" + response[0].name + "</a></h4></span>" +
          "<span class='oswald'><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/subtopics/" + response[1].id + "'>" + response[1].name + "</a></h4></span>" +
          "<span class='oswald'><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/subtopics/" + response[2].id + "'>" + response[2].name + "</a></h4></span>" +
          "<span class='oswald'><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/subtopics/" + response[3].id + "'>" + response[3].name + "</a></h4></span>" +
          "<span class='oswald'><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/subtopics/" + response[4].id + "'>" + response[4].name + "</a></h4></span>" +
          "<span class='oswald'><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/subtopics/" + response[5].id + "'>" + response[5].name + "</a></h4></span>"+
          "<span class='oswald'><h4 class='oswald'><a href='http://partyoncode.herokuapp.com/subtopics/" + response[6].id + "'>" + response[6].name + "</a></h4></span>"
          

      );

    });

  });

  </script>

app/views/topics/new.html.erb
<%= form_for @topic do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit "Add Topic!" %>
  </div> 
<%end%>

app/views/topics/show.html.erb
<h1 class="col-md-offset-2 col-md-8 text-center subtitle row"><%= @topic.name %></h1></br>

  <% if current_user %>

    <div class="modal fade" id="add-link-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Add a New Link!</h4>
            </div>
            <div class="modal-body">
              <%= render 'links/form', object: @link %>
            </div>
          </div>
        </div>
      </div>


      <div class="col-md-offset-2 col-md-8 text-center">
        <button type="button" class="btn btn-custom btn-lg text-center" data-toggle="modal" data-target="#add-link-modal">Add a Link</button>
      </div>


  <% end %>

  <div class="col-md-6 text-left main-list">
   <% @links.order(:cached_votes_total => :desc).each do |link| %>

  <!--  	We want to display the links that belong to each of @topic's subtopics, so we put @links = Link.all in the show method of the topics controller, and we're using this conditional statement to show only the links that belong to a subtopic which belongs to the current topic page -->
   		<% if link.subtopic.topic_id == @topic.id %>
  				<ul class="list-unstyled">
  					<li><h4><a href="<%=link.url %>"><%= fetch(link.url.to_s).title %></a></h4></li>
  					<li><%= fetch(link.url.to_s).description %></li>
  					<li><img class="link-img" src="<%= fetch(link.url.to_s).images.first.src %>"></li>
  			    <li><%= link.try(:subtopic).try(:name) %></li>
  			        <!-- the code below allows administrators to delete a link from the index; the link does not show up on the page for users who are not a administrator -->
  					<li><% if current_user.try(:admin?)%><%= link_to 'Delete', link_path(link), method: :delete, data: { confirm: 'Are you sure?' } %><%end%></li>
  					<!-- Displays the user name of the user who posted the link -->
  			   <!--  <li><%#= link.user.name %></li>   --> 
  			    <li><%= link_to "Comments", link_path(link) %> || (<%= link.comments.count %>)</li>   
  			    	
  			    	<!-- The following block of code allows a user to upvote a link and tallies the specific link's upvotes  -->
  			   	<li>
  			    		<%= link_to like_link_path(link), method: :put do %>
  			    			
  			    			Upvote
  			    	
  			    			<%= link.get_upvotes.size %>

  			    		<% end %> 
  			    </li>
  				</ul> 
   		<% end %>


   	<% end %>

	</div>

<div class=" col-md-5 text-right sidebar">
  <h3><%= @topic.name %> Subtopics</h3>
  <ul class="list-unstyled">
    <% @topic.subtopics.each do |subtopic| %>
      <li><h4><%= link_to subtopic.name, subtopic_path(subtopic) %></h4></li>
    <% end %>
  </ul>
</div>

<div class=" col-md-5 text-right sidebar">
  <h3>All Topics</h3>
  <ul class="list-unstyled">
    <% @topics.each do |topic| %>
      <li><h4><%= link_to topic.name, topic_path(topic) %></h4></li>
    <% end %>
  </ul>
</div>