config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root to: "topics#index"

  get 'users/' => 'users#index'

  
  get 'users/:id' => 'users#show', as: :user

  post 'users/' => 'users#create'

  get 'users/:id/edit' => 'users#edit', as: :edit_user
  
  patch 'users/:id' => 'users#update', as: :update_user

  delete 'users/:id' => 'users#destroy'

  
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
  end

  resources :topics do
    resources :subtopics
  end

  get "/subtopics/:id" => 'subtopics#show', as: :subtopic
  get "/subtopics/new" => "subtopics#new", as: :subtopics
  post "/subtopics/new" => "subtopics#create"

    resources :links do
      member do 
        put "like", to: "links#upvote"
      end 
      resources :comments, except: :index
    end  

    namespace :api do
        resources :links, only: [:index, :create, :show], defaults: {format: "json"}
        resources :topics, only: [:index, :create, :show], defaults: {format: "json"}
        resources :subtopics, except: [:topic_id], defaults: {format: "json"}
    end

    

  

  
  
  
  
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Source+Code+Pro' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <title>POC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


		<nav class="navbar nav-style">
			<h1 class="col-md-6 text-center"><%= link_to "party ", root_path, :class => "green" %><%= link_to "( ", root_path, :class => "white" %><%= link_to "on", root_path, :class => "orange" %><%= link_to " ) { ", root_path, :class => "white" %><%= link_to "code", root_path, :class => "red" %><%= link_to " };", root_path, :class => "white" %></h1>
			<% if user_signed_in? %>
			   		<ul id="nav-list" class="col-md-5 list-unstyled list-inline text-right">
							<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	          <!-- added link to user profile so that a user could see what links they have upvoted  -->
		   	      <li><%= link_to "Your Profile", user_path(current_user) %> </li>
		   	      <li><%= link_to "All Links", links_path %>
					</ul>
			<% else %>
			   	<ul id="nav-list-signin" class="col-md-5 list-unstyled list-inline text-right">
						<li><%= link_to "Sign In", signin_path %></li>
						<li><%= link_to "All Links", links_path %>
					</ul>
			<% end %>
		</nav>	





		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		




<%= yield %>



<nav id="footer" class="navbar nav-style navbar-fixed-bottom">
	 <div class="col-md-11 text-center party-function">

   
    <h2><span class="red">for</span><span class="white">( </span><span class="blue"> var i</span><span class="white"> = </span><span class="red">0</span><span class="white">; i</span><span class="red"> &lt; </span><span class="white"> ∞; i</span><span class="red"> ++</span><span class="white">) {<span></span>

   <!--  <img src="http://www.sixstringtheories.com/wp-content/uploads/2012/04/mocha-dad-friday-night-party-on-twitter.jpg" class="party-img inline-block"> -->

    <span class=" white"><span class="red">return </span>Party Time;}</span>

    
    </h2>

  </div>
</nav>





</body>
</html>